name: AxTrade
version: '${project.version}'
main: com.artillexstudios.axtrade.AxTrade
api-version: '1.18'
folia-supported: true

permissions:
  axtrade.admin:
    default: op
  axtrade.trade:
    default: true